# 開発環境構築用

version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/development/go/Dockerfile
    volumes:
      - .:/go/src/app
    environment:
      GO111MODULE: "on"
    links:
      - db
    depends_on:
      - db
    expose:
      - "8080"

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"

  nginx:
    build:
      context: docker/development/nginx
    volumes:
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443
    links:
      - web

volumes:
  db: {}
